# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # download python
      - name: set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      # Install dependencies
      - name: Get dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "./Text Files/requirements.txt"

      # Run tests
      - name: Run unit tests
        run: python -m unittest discover "./Unit Tests"

  notify_steve:
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@master
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
        with:
          args: "@ScreaminSteve#
  
